# Generated by Django 4.2.1 on 2026-08-31 12:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff_member', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cover_image', models.ImageField(upload_to='books/')),
                ('description', models.TextField()),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'National Book Registry',
            },
        ),
        migrations.CreateModel(
            name='NationalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (UGX)')),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('stock_available', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'National Book Registry',
                'verbose_name_plural': 'National Book Registry',
            },
        ),
        migrations.CreateModel(
            name='NationalTopPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='performers/')),
            ],
        ),
        migrations.CreateModel(
            name='NationalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('date_found', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NATIONAL LIVE FEED',
                'ordering': ['-date_found'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('unique_code', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('school_motto', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(choices=[('PRIMARY', 'Primary Level (PLE System)'), ('SECONDARY', 'Secondary Level (UCE/UACE System)'), ('VOCATIONAL', 'Vocational/Technical (DIT/BTVET)'), ('UNIVERSITY', 'Higher Education (NCHE/CGPA)'), ('INTERNATIONAL', 'International (Year 1 - Year 13)')], default='SECONDARY', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(default='Kampala', max_length=100)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Official Email')),
                ('school_account_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('school_code', models.CharField(blank=True, help_text='Provided by SchoolPay', max_length=100)),
                ('uneb_center_number', models.CharField(default='U0000', max_length=20)),
                ('api_password', models.CharField(blank=True, max_length=255)),
                ('total_revenue_collected', models.BigIntegerField(default=0)),
                ('total_commission_earned', models.BigIntegerField(default=0)),
                ('rating', models.CharField(default='⭐⭐⭐⭐⭐', max_length=30)),
                ('mission', models.TextField(default='To provide high-quality education.')),
                ('vision', models.TextField(default='A lead institution of excellence.')),
                ('core_values', models.TextField(default='Integrity, Excellence, Discipline')),
                ('followers_count', models.IntegerField(default=1500)),
                ('term_end_date', models.CharField(default='05th Dec 2026', max_length=100)),
                ('next_term_start', models.CharField(default='02nd Feb 2027', max_length=100)),
                ('is_verified', models.BooleanField(default=False, verbose_name='National Approval Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stamp_color', models.CharField(default='#002366', max_length=20)),
                ('keb_logo', models.ImageField(blank=True, null=True, upload_to='logos/keb/')),
                ('chairman_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('ussd_instructions', models.TextField(default='Dial *165#...')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('national_id_copy', models.ImageField(blank=True, null=True, upload_to='staff/ids/')),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='staff/cvs/')),
                ('staff_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('secure_pin', models.CharField(blank=True, editable=False, max_length=4)),
                ('role', models.CharField(choices=[('TEACHER', 'Class Teacher'), ('BURSAR', 'School Bursar'), ('HEADTEACHER', 'Head Teacher'), ('DIRECTOR', 'School Director'), ('SECRETARY', 'Front Desk/Secretary'), ('LIBRARIAN', 'Library Manager')], default='TEACHER', max_length=20)),
                ('tin_number', models.CharField(blank=True, max_length=30, verbose_name='URA TIN')),
                ('nssf_number', models.CharField(blank=True, max_length=30, verbose_name='NSSF No.')),
                ('next_of_kin', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(default='Instructor', max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('momo_number', models.CharField(blank=True, max_length=30, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registry', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('age', models.IntegerField(default=15)),
                ('current_class', models.CharField(max_length=50)),
                ('payment_code', models.CharField(blank=True, db_index=True, help_text="Student's SchoolPay PRN", max_length=100, null=True, unique=True)),
                ('school_code', models.CharField(blank=True, help_text='Provided by SchoolPay', max_length=100)),
                ('stream', models.CharField(default='North', max_length=50)),
                ('account_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('level_category', models.CharField(default='UCE_NEW', max_length=20)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='docs/birth/')),
                ('ple_result_slip', models.FileField(blank=True, null=True, upload_to='docs/ple/')),
                ('uce_result_slip', models.FileField(blank=True, null=True, upload_to='docs/uce/')),
                ('admission_letter', models.FileField(blank=True, null=True, upload_to='docs/admission/')),
                ('initial_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active in Registry')),
                ('parent_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in_school', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('level', models.CharField(choices=[('PLE', 'Primary Level (PLE)'), ('UCE', 'Ordinary Level (UCE)'), ('UACE', 'Advanced Level (UACE)'), ('OTHER', 'Vocational/Other')], default='UCE', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_o_level', models.BooleanField(default=True)),
                ('is_a_level', models.BooleanField(default=False)),
                ('combination_tag', models.CharField(blank=True, help_text='e.g. BCM, HEG', max_length=10, null=True)),
                ('is_core', models.BooleanField(default=True, help_text='Is this a compulsory subject?')),
                ('combination_category', models.CharField(blank=True, help_text='e.g., Sciences, Humanities, Languages', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'NATIONAL SUBJECT REGISTRY',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(default=2026)),
                ('current_term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('system_logo', models.ImageField(upload_to='system/')),
            ],
            options={
                'verbose_name': 'Global System Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_school_admin', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='api.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='Tuition', max_length=100)),
                ('amount_paid', models.FloatField(default=0)),
                ('system_tax', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.school')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_class', models.CharField(help_text='e.g., S.1 North', max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'verbose_name': 'Subject Assignment',
                'verbose_name_plural': 'Subject Assignments',
            },
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Salary')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PAYE/Tax')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid/Disbursed')], default='PENDING', max_length=20)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='api.staff')),
            ],
            options={
                'verbose_name': 'STAFF PAYROLL RECORD',
                'verbose_name_plural': 'STAFF PAYROLL RECORDS',
            },
        ),
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=2026)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PAYE (URA)')),
                ('nssf_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='NSSF (5%)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='api.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='api.subject'),
        ),
        migrations.CreateModel(
            name='SchoolPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School')], default='SECONDARY', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(upload_to='feed/')),
                ('likes_count', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPayLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_printed', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, null=True)),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Transaction Void')),
                ('reversal_reason', models.TextField(blank=True, help_text='Why was this reversed?', null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'verbose_name': '🛡️ SCHOOLPAY LEDGER',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(default='Standard Excellence', max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='templates/bg/')),
                ('opacity', models.FloatField(default=0.05)),
                ('theme_color', models.CharField(default='Royal Gold', max_length=50)),
                ('page_frame_enabled', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': 'REPORT DESIGNER VAULT',
            },
        ),
        migrations.CreateModel(
            name='NationalDataBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='national_bridge/files/')),
                ('preview_data', models.JSONField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('records_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': 'NATIONAL DATA BRIDGE',
                'verbose_name_plural': 'NATIONAL DATA BRIDGE',
            },
        ),
        migrations.CreateModel(
            name='NationalBookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(help_text='GPS or School Address', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('escrow_fee', models.DecimalField(decimal_places=2, help_text='10% Deposit', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pay'), ('PAID', 'Escrow Confirmed'), ('DISPATCHED', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nationalbook')),
            ],
            options={
                'verbose_name': 'Book Order Management',
                'verbose_name_plural': 'Book Order Management',
            },
        ),
        migrations.CreateModel(
            name='KEBMockResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('points', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keb_results', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'verbose_name': 'KEB MOCK RESULT',
                'verbose_name_plural': 'KEB MOCK RESULTS',
            },
        ),
        migrations.CreateModel(
            name='FeesTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_tracker', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='DataExchangeHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_file', models.FileField(upload_to='exchange/files/')),
                ('category', models.CharField(choices=[('STUDENTS', 'Student Bio'), ('MARKS', 'Academic Marks'), ('FEES', 'Financial Ledger')], default='STUDENTS', max_length=20)),
                ('exchange_type', models.CharField(choices=[('IMPORT', 'Import to System'), ('EXPORT', 'Export from Registry')], default='IMPORT', max_length=10)),
                ('processed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': 'National Data Exchange',
                'verbose_name_plural': 'National Data Exchange',
            },
        ),
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('message_type', models.CharField(choices=[('SMS', 'SMS Text'), ('WHATSAPP', 'WhatsApp Message')], default='SMS', max_length=10)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': 'COMMUNICATION LOGS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('is_escrow_paid', models.BooleanField(default=False, help_text='10% commitment fee paid?')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
        ),
        migrations.CreateModel(
            name='BioAndCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_career', models.CharField(default='Leader', max_length=255)),
                ('challenges_faced', models.TextField(default='None')),
                ('student_inspiration', models.TextField(default='Uganda')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, help_text="e.g. 'Arrived at 9AM'", max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.student')),
            ],
            options={
                'verbose_name': 'DAILY ATTENDANCE',
                'verbose_name_plural': 'DAILY ATTENDANCE',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AcademicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi_1', models.FloatField(default=0)),
                ('aoi_2', models.FloatField(default=0)),
                ('aoi_3', models.FloatField(default=0)),
                ('aoi_4', models.FloatField(default=0)),
                ('mid_term', models.FloatField(default=0)),
                ('eot_score', models.FloatField(default=0)),
                ('project_work', models.FloatField(default=0)),
                ('aoi_1_max', models.IntegerField(default=10)),
                ('aoi_2_max', models.IntegerField(default=10)),
                ('aoi_3_max', models.IntegerField(default=10)),
                ('aoi_4_max', models.IntegerField(default=10)),
                ('mid_max', models.IntegerField(default=100)),
                ('eot_max', models.IntegerField(default=100)),
                ('project_max', models.IntegerField(default=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Which school does this administrator manage?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='AcademicResultsCenter',
            fields=[
            ],
            options={
                'verbose_name_plural': 'ACADEMIC HUB (MASTER GRID)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='AttendanceHub',
            fields=[
            ],
            options={
                'verbose_name': 'MARK DAILY ATTENDANCE',
                'verbose_name_plural': 'MARK DAILY ATTENDANCE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.attendance',),
        ),
        migrations.CreateModel(
            name='BursarTerminal',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL BURSAR TERMINAL',
                'verbose_name_plural': 'NATIONAL BURSAR TERMINAL',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='CommissionAnalytics',
            fields=[
            ],
            options={
                'verbose_name_plural': 'MY COMMISSION TRACKER',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='DataExchangeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Import & Export Center',
                'verbose_name_plural': 'Import & Export Center',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.dataexchangehub',),
        ),
        migrations.CreateModel(
            name='FeesReminder',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL FEES REMINDERS',
                'verbose_name_plural': 'NATIONAL FEES REMINDERS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='FinancialCommandCenter',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL FINANCIAL COMMAND',
                'verbose_name_plural': 'NATIONAL FINANCIAL COMMAND',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='KEBMockPortal',
            fields=[
            ],
            options={
                'verbose_name': 'KEB MOCKS CENTER',
                'verbose_name_plural': 'KEB MOCKS CENTER',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='NationalLedger',
            fields=[
            ],
            options={
                'verbose_name_plural': 'NATIONAL UNEDITABLE LEDGER',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.transaction',),
        ),
        migrations.CreateModel(
            name='NationalMeritList',
            fields=[
            ],
            options={
                'verbose_name': 'National Merit List',
                'verbose_name_plural': 'National Merit List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='OperationsHub',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL OPERATIONS HUB',
                'verbose_name_plural': 'NATIONAL OPERATIONS HUB',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='PayrollCommand',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL STAFF PAYROLL',
                'verbose_name_plural': 'NATIONAL STAFF PAYROLL',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.staffsalary',),
        ),
        migrations.CreateModel(
            name='PerformanceAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL PERFORMANCE ANALYTICS',
                'verbose_name_plural': 'NATIONAL PERFORMANCE ANALYTICS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='SovereignParentRegistry',
            fields=[
            ],
            options={
                'verbose_name': 'SOVEREIGN PARENT REGISTRY',
                'verbose_name_plural': 'SOVEREIGN PARENT REGISTRY',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.parent',),
        ),
        migrations.CreateModel(
            name='SovereignProfessionalInsights',
            fields=[
            ],
            options={
                'verbose_name_plural': 'SOVEREIGN ANALYTICS (PRO)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='SovereignRegistry',
            fields=[
            ],
            options={
                'verbose_name': 'SOVEREIGN NATIONAL REGISTRY',
                'verbose_name_plural': 'SOVEREIGN NATIONAL REGISTRY',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
    ]
