# Generated by Django 4.2.1 on 2026-07-07 11:02

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTopPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='performers/')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('unique_code', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('sector', models.CharField(choices=[('PRIMARY', 'Primary Level (PLE System)'), ('SECONDARY', 'Secondary Level (UCE/UACE System)'), ('VOCATIONAL', 'Vocational/Technical (DIT/BTVET)'), ('UNIVERSITY', 'Higher Education (NCHE/CGPA)')], default='SECONDARY', max_length=20)),
                ('stamp_color', models.CharField(default='#002366', help_text='Hex color for digital stamp', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(default='Kampala', max_length=100)),
                ('school_motto', models.CharField(max_length=255)),
                ('school_account_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('uneb_center_number', models.CharField(default='U0000', max_length=20)),
                ('school_type', models.CharField(default='Secondary / Boarding', max_length=100)),
                ('rating', models.CharField(default='⭐⭐⭐⭐⭐', max_length=30)),
                ('mission', models.TextField(default='To provide high-quality education.')),
                ('vision', models.TextField(default='A lead institution of excellence.')),
                ('core_values', models.TextField(default='Integrity, Excellence, Discipline')),
                ('ussd_instructions', models.TextField(default='1. Dial *165# (MTN) or *185# (Airtel)\n2. Select Fees & SchoolPay\n3. Select Pay Fees\n4. Enter PRN', help_text='Provide step-by-step dialing instructions for the Parent App')),
                ('school_code', models.CharField(blank=True, max_length=100)),
                ('api_password', models.CharField(blank=True, max_length=255)),
                ('total_revenue_collected', models.BigIntegerField(default=0)),
                ('total_commission_earned', models.BigIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True)),
                ('followers_count', models.IntegerField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('national_id_copy', models.ImageField(blank=True, null=True, upload_to='staff/ids/')),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='staff/cvs/')),
                ('staff_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('secure_pin', models.CharField(blank=True, max_length=6)),
                ('tin_number', models.CharField(blank=True, max_length=30, verbose_name='URA TIN')),
                ('nssf_number', models.CharField(blank=True, max_length=30, verbose_name='NSSF No.')),
                ('next_of_kin', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(default='Instructor', max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('momo_number', models.CharField(blank=True, max_length=30, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registry', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('age', models.IntegerField(default=15)),
                ('current_class', models.CharField(max_length=50)),
                ('payment_code', models.CharField(blank=True, help_text="Student's SchoolPay PRN", max_length=100, null=True, unique=True)),
                ('school_code', models.CharField(blank=True, help_text='Provided by SchoolPay', max_length=100)),
                ('stream', models.CharField(default='North', max_length=50)),
                ('account_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('level_category', models.CharField(default='UCE_NEW', max_length=20)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='docs/birth/')),
                ('ple_result_slip', models.FileField(blank=True, null=True, upload_to='docs/ple/')),
                ('uce_result_slip', models.FileField(blank=True, null=True, upload_to='docs/uce/')),
                ('admission_letter', models.FileField(blank=True, null=True, upload_to='docs/admission/')),
                ('initial_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active in Registry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('level', models.CharField(choices=[('PLE', 'Primary Level (PLE)'), ('UCE', 'Ordinary Level (UCE)'), ('UACE', 'Advanced Level (UACE)'), ('OTHER', 'Vocational/Other')], default='UCE', max_length=10)),
                ('is_core', models.BooleanField(default=True, help_text='Is this a compulsory subject?')),
                ('combination_category', models.CharField(blank=True, help_text='e.g., Sciences, Humanities, Languages', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'National Subject Registry',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='Tuition', max_length=100)),
                ('amount_paid', models.FloatField(default=0)),
                ('system_tax', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.school')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_class', models.CharField(help_text='e.g., S.1 North', max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'verbose_name': 'Subject Assignment',
                'verbose_name_plural': 'Subject Assignments',
            },
        ),
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=2026)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PAYE (URA)')),
                ('nssf_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='NSSF (5%)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School')], default='SECONDARY', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(upload_to='feed/')),
                ('likes_count', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPayLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_printed', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'verbose_name': '🛡️ SCHOOLPAY LEDGER',
            },
        ),
        migrations.CreateModel(
            name='FeesTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_tracker', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='BioAndCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_career', models.CharField(default='Leader', max_length=255)),
                ('challenges_faced', models.TextField(default='None')),
                ('student_inspiration', models.TextField(default='Uganda')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, help_text="e.g. 'Arrived at 9AM'", max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.student')),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendance',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AcademicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi_1', models.FloatField(default=0)),
                ('aoi_2', models.FloatField(default=0)),
                ('aoi_3', models.FloatField(default=0)),
                ('aoi_4', models.FloatField(default=0)),
                ('mid_term', models.FloatField(default=0)),
                ('eot_score', models.FloatField(default=0)),
                ('project_work', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff_member', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('school', models.ForeignKey(blank=True, help_text='Which school does this administrator manage?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicResultsCenter',
            fields=[
            ],
            options={
                'verbose_name_plural': '📊 ACADEMIC HUB (MASTER GRID)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='AttendanceHub',
            fields=[
            ],
            options={
                'verbose_name': '✅ MARK DAILY ATTENDANCE',
                'verbose_name_plural': '✅ MARK DAILY ATTENDANCE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.attendance',),
        ),
        migrations.CreateModel(
            name='BursarTerminal',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL BURSAR TERMINAL',
                'verbose_name_plural': 'NATIONAL BURSAR TERMINAL',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='CommissionAnalytics',
            fields=[
            ],
            options={
                'verbose_name_plural': '💰 MY COMMISSION TRACKER',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='FinancialCommandCenter',
            fields=[
            ],
            options={
                'verbose_name': '📊 NATIONAL FINANCIAL COMMAND',
                'verbose_name_plural': '📊 NATIONAL FINANCIAL COMMAND',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='NationalLedger',
            fields=[
            ],
            options={
                'verbose_name_plural': '🛡️ NATIONAL UNEDITABLE LEDGER',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.transaction',),
        ),
        migrations.CreateModel(
            name='OperationsHub',
            fields=[
            ],
            options={
                'verbose_name': '0. NATIONAL OPERATIONS HUB',
                'verbose_name_plural': '0. NATIONAL OPERATIONS HUB',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='SovereignProfessionalInsights',
            fields=[
            ],
            options={
                'verbose_name_plural': '⭐ SOVEREIGN ANALYTICS (PRO)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='SovereignRegistry',
            fields=[
            ],
            options={
                'verbose_name': 'Sovereign National Registry',
                'verbose_name_plural': 'Sovereign National Registry',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
    ]
