# Generated by Django 4.2.1 on 2026-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NationalUpdate',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'System Access Keys', 'verbose_name_plural': 'System Access Keys'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='generated_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
