# Generated by Django 4.2.1 on 2026-07-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationaldatabridge',
            options={'verbose_name': '3. National Data Bridge', 'verbose_name_plural': '3. National Data Bridge'},
        ),
        migrations.RemoveField(
            model_name='nationaldatabridge',
            name='processed_date',
        ),
        migrations.AddField(
            model_name='nationaldatabridge',
            name='preview_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nationaldatabridge',
            name='records_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationaldatabridge',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
