# Generated by Django 4.2.1 on 2026-08-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_verified',
        ),
    ]
