# Generated by Django 4.2.1 on 2026-08-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='keb_logo_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
