# Generated by Django 4.2.1 on 2026-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationaldatabridge',
            options={'verbose_name': 'National Data Bridge', 'verbose_name_plural': 'National Data Bridge'},
        ),
        migrations.RemoveField(
            model_name='nationaldatabridge',
            name='records_synced',
        ),
        migrations.RemoveField(
            model_name='nationaldatabridge',
            name='source_pdf',
        ),
        migrations.RemoveField(
            model_name='nationaldatabridge',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='nationaldatabridge',
            name='processed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nationaldatabridge',
            name='source_file',
            field=models.FileField(default=1, upload_to='national_bridge/files/'),
            preserve_default=False,
        ),
    ]
