# Generated by Django 4.2.1 on 2026-07-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationshub',
            options={'verbose_name': 'NATIONAL OPERATIONS HUB', 'verbose_name_plural': 'NATIONAL OPERATIONS HUB'},
        ),
    ]
