# Generated by Django 4.2.1 on 2026-08-31 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='school',
            name='chairman_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='keb_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/keb/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='stamp_color',
            field=models.CharField(default='#002366', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='ussd_instructions',
            field=models.TextField(default='Dial *165#...'),
        ),
    ]
