# Generated by Django 4.2.1 on 2026-08-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalMeritList',
            fields=[
            ],
            options={
                'verbose_name': 'National Merit List',
                'verbose_name_plural': 'National Merit List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
    ]
