# Generated by Django 4.2.1 on 2026-08-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='core_values',
        ),
        migrations.RemoveField(
            model_name='school',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='school',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='school',
            name='next_term_start',
        ),
        migrations.RemoveField(
            model_name='school',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_account_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_type',
        ),
        migrations.RemoveField(
            model_name='school',
            name='stamp_color',
        ),
        migrations.RemoveField(
            model_name='school',
            name='term_end_date',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vision',
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, default='+256', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='chairman_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='keb_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/keb/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_motto',
            field=models.CharField(default='Excellence', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='sector',
            field=models.CharField(default='SECONDARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='ussd_instructions',
            field=models.TextField(default='Dial *165#...'),
        ),
    ]
