# Generated by Django 4.2.1 on 2026-08-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_2_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_3_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_4_max',
            field=models.IntegerField(default=10),
        ),
    ]
