# Generated by Django 4.2.1 on 2026-08-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='National Approval Status'),
        ),
    ]
