# Generated by Django 6.0.5 on 2026-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name': 'Academic Result Hub', 'verbose_name_plural': 'Academic Results Hub (Single Entry)'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='is_national_topper',
            new_name='is_topper',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_top_teaching',
        ),
        migrations.RemoveField(
            model_name='school',
            name='national_rating',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_motto',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sports_music',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teaching_style',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district_rank',
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(default='Knowledge is Power', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='vision',
            field=models.TextField(default='Leading Center of Excellence'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI 1'), ('AOI2', 'AOI 2'), ('MidTerm', 'Mid-Term'), ('AOI3', 'AOI 3'), ('AOI4', 'AOI 4'), ('EOT', 'End of Term'), ('Project', 'Project')], default='AOI1', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='achievements',
            field=models.TextField(default='National Champions'),
        ),
    ]
