# Generated by Django 4.2.1 on 2026-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationaldatabridge',
            options={'verbose_name': 'National Data Bridge', 'verbose_name_plural': 'National Data Bridge'},
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Class Teacher'), ('BURSAR', 'School Bursar'), ('HEADTEACHER', 'Head Teacher'), ('DIRECTOR', 'School Director'), ('SECRETARY', 'Front Desk/Secretary'), ('LIBRARIAN', 'Library Manager')], default='TEACHER', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Select subjects taught by this staff', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='secure_pin',
            field=models.CharField(editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
