# Generated by Django 4.2.1 on 2026-08-28 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline'),
        ),
        migrations.AddField(
            model_name='school',
            name='followers_count',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide high-quality education.'),
        ),
        migrations.AddField(
            model_name='school',
            name='next_term_start',
            field=models.CharField(default='02nd Feb 2027', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.CharField(default='⭐⭐⭐⭐⭐', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='school_account_id',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='stamp_color',
            field=models.CharField(default='#002366', help_text='Hex color for digital stamp', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='term_end_date',
            field=models.CharField(default='05th Dec 2026', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='vision',
            field=models.TextField(default='A lead institution of excellence.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='chairman_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Chairman Signature'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Official Email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='keb_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/keb/', verbose_name='Official KEB Logo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(default='+256', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, help_text='Provided by SchoolPay', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_motto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='sector',
            field=models.CharField(choices=[('PRIMARY', 'Primary Level (PLE System)'), ('SECONDARY', 'Secondary Level (UCE/UACE System)'), ('VOCATIONAL', 'Vocational/Technical (DIT/BTVET)'), ('UNIVERSITY', 'Higher Education (NCHE/CGPA)'), ('INTERNATIONAL', 'International (Year 1 - Year 13)')], default='SECONDARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='ussd_instructions',
            field=models.TextField(default='1. Dial *165# (MTN) or *185# (Airtel)\n2. Select Fees & SchoolPay\n3. Select Pay Fees\n4. Enter PRN', help_text='Step-by-step instructions for the Parent App'),
        ),
    ]
