# Generated by Django 4.2.1 on 2026-07-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cover_image', models.ImageField(upload_to='books/')),
                ('description', models.TextField()),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'National Book Registry',
            },
        ),
        migrations.CreateModel(
            name='FeesReminder',
            fields=[
            ],
            options={
                'verbose_name': 'National Fees Reminders',
                'verbose_name_plural': 'National Fees Reminders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('is_escrow_paid', models.BooleanField(default=False, help_text='10% commitment fee paid?')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
        ),
    ]
