# Generated by Django 4.2.1 on 2026-08-30 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('date_found', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NATIONAL LIVE FEED',
                'ordering': ['-date_found'],
            },
        ),
        migrations.RemoveField(
            model_name='school',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='generated_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='api.school'),
            preserve_default=False,
        ),
    ]
