# Generated by Django 4.2.1 on 2026-08-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_academicresult_aoi_2_academicresult_aoi_2_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Official Email'),
        ),
        migrations.AddField(
            model_name='school',
            name='next_term_start',
            field=models.CharField(default='02nd Feb 2027', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone'),
        ),
        migrations.AddField(
            model_name='school',
            name='term_end_date',
            field=models.CharField(default='05th Dec 2026', max_length=100),
        ),
    ]
