# Generated by Django 6.0.5 on 2026-05-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_academicresultscenter_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name_plural': 'Academic Results Hub (Single Entry)'},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='motto',
            new_name='school_motto',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='is_topper',
            new_name='is_national_topper',
        ),
        migrations.RemoveField(
            model_name='school',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='future_career',
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_rank',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_comment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_fees_due',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_fees_paid',
        ),
        migrations.AddField(
            model_name='school',
            name='is_top_teaching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='national_rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='school',
            name='school_achievements',
            field=models.TextField(default='Leading in academic standards.'),
        ),
        migrations.AddField(
            model_name='student',
            name='ai_competency_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI 1'), ('AOI2', 'AOI 2'), ('MidTerm', 'Mid-Term'), ('AOI3', 'AOI 3'), ('AOI4', 'AOI 4'), ('EOT', 'End of Term')], default='AOI1', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(default='Kampala, Uganda', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Primary', 'Primary (PLE)'), ('Secondary_O', 'Secondary (CBC)'), ('Secondary_A', 'Secondary (UNEB)'), ('International', 'International'), ('Higher', 'University/Vocational')], max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='To be a center of excellence.'),
        ),
        migrations.AlterField(
            model_name='schoolpost',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='unsc_national_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='unsc_national_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='BioAndCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_career', models.CharField(default='Professional', max_length=255)),
                ('achievements', models.TextField(default='Active Learner')),
                ('student_comment', models.TextField(default='Ready to lead.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='api.student')),
            ],
            options={
                'verbose_name_plural': 'Bio and Career',
            },
        ),
        migrations.CreateModel(
            name='FeesTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees_due', models.IntegerField(default=1200000)),
                ('total_fees_paid', models.IntegerField(default=0)),
                ('teacher_remark', models.TextField(default='Performing well.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='api.student')),
            ],
            options={
                'verbose_name_plural': 'Fees Status',
            },
        ),
        migrations.CreateModel(
            name='NationalRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_rank', models.IntegerField(default=0)),
                ('district_rank', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='api.student')),
            ],
            options={
                'verbose_name_plural': 'National Ranking',
            },
        ),
    ]
