# Generated by Django 4.2.1 on 2026-07-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_operationshub_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_pdf', models.FileField(upload_to='ingestion/pdfs/')),
                ('processed', models.BooleanField(default=False)),
                ('total_records', models.IntegerField(default=0, help_text='Number of students imported')),
                ('import_log', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': '1. National Data Ingestion',
                'verbose_name_plural': '1. National Data Ingestion',
            },
        ),
    ]
