# Generated by Django 4.2.1 on 2026-09-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_school_keb_logo_data_school_logo_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'verbose_name': 'Sovereign Design Vault'},
        ),
        migrations.RenameField(
            model_name='reporttemplate',
            old_name='page_frame_enabled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='reporttemplate',
            old_name='opacity',
            new_name='watermark_opacity',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='design_name',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='border_thickness',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='page_format',
            field=models.CharField(choices=[('A4', 'A4 Standard'), ('A5', 'A5 Mini (A-One)'), ('A3', 'A3 Poster'), ('LEGAL', 'Legal Size')], default='A4', max_length=10),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='primary_color',
            field=models.CharField(default='#002366', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='secondary_color',
            field=models.CharField(default='#D4AF37', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='target_type',
            field=models.CharField(choices=[('REPORT', 'School Report Card'), ('KEB', 'KEB Mock Passlip')], default='REPORT', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='use_school_logo_as_watermark',
            field=models.BooleanField(default=True),
        ),
    ]
