# Generated by Django 4.2.1 on 2026-08-30 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_options_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='school',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='National Approval Status'),
        ),
    ]
