# Generated by Django 4.2.1 on 2026-07-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_nationaldatabridge_options_staff_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.parent'),
        ),
    ]
