# Generated by Django 4.2.1 on 2026-07-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_feesreminder_bookorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovereignParentRegistry',
            fields=[
            ],
            options={
                'verbose_name': 'Sovereign Parent Registry',
                'verbose_name_plural': 'Sovereign Parent Registry',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.parent',),
        ),
    ]
