# Generated by Django 4.2.1 on 2026-08-30 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nationalmeritlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffsalary',
            options={'verbose_name': 'STAFF PAYROLL RECORD', 'verbose_name_plural': 'STAFF PAYROLL RECORDS'},
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='school',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Approved by National Centre'),
        ),
    ]
