# Generated by Django 4.2.1 on 2026-07-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sovereignparentregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpayledger',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='Transaction Void'),
        ),
        migrations.AddField(
            model_name='schoolpayledger',
            name='reversal_reason',
            field=models.TextField(blank=True, help_text='Why was this reversed?', null=True),
        ),
        migrations.AddField(
            model_name='schoolpayledger',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
