# Generated by Django 4.2.1 on 2026-08-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_school_email_school_next_term_start_school_phone2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KEBMockPortal',
            fields=[
            ],
            options={
                'verbose_name': 'KEB MOCKS CENTER',
                'verbose_name_plural': 'KEB MOCKS CENTER',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='KEBMockResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('points', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keb_results', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'verbose_name': 'KEB MOCK RESULT',
                'verbose_name_plural': 'KEB MOCK RESULTS',
            },
        ),
    ]
