# Generated by Django 6.0.5 on 2026-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_academicresultscenter_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioandcareer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feestracker',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nationalranking',
            options={},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_motto',
            new_name='motto',
        ),
        migrations.RemoveField(
            model_name='feestracker',
            name='teacher_remark',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_achievements',
        ),
        migrations.AddField(
            model_name='school',
            name='achievements',
            field=models.TextField(default='National Champions'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI 1'), ('AOI2', 'AOI 2'), ('MidTerm', 'Mid-Term'), ('AOI3', 'AOI 3'), ('AOI4', 'AOI 4'), ('EOT', 'End of Term'), ('Project', 'Project')], default='AOI1', max_length=20),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_comment',
            field=models.TextField(default='Excellence is a choice.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(default='Uganda', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Primary', 'Primary/PLE'), ('Secondary_O', 'Secondary (CBC)'), ('Secondary_A', 'Secondary (UNEB)'), ('International', 'International'), ('Higher', 'University')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='unsc_final_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='unsc_final_perms', to='auth.permission'),
        ),
    ]
