# Generated by Django 4.2.1 on 2026-07-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dataingestionvault'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataIngestionVault',
        ),
    ]
