# Generated by Django 4.2.1 on 2026-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attendance_date_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['level', 'name'], 'verbose_name': 'National Subject Registry'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='combination_category',
            field=models.CharField(blank=True, help_text='e.g., Sciences, Humanities, Languages', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_core',
            field=models.BooleanField(default=True, help_text='Is this a compulsory subject?'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('PLE', 'Primary Level (PLE)'), ('UCE', 'Ordinary Level (UCE)'), ('UACE', 'Advanced Level (UACE)'), ('OTHER', 'Vocational/Other')], default='UCE', max_length=10),
        ),
    ]
