# Generated by Django 4.2.1 on 2026-07-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_schoolpayledger_is_reversed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(default=2026)),
                ('current_term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('system_logo', models.ImageField(upload_to='system/')),
            ],
            options={
                'verbose_name': 'Global System Settings',
            },
        ),
    ]
