# Generated by Django 4.2.1 on 2026-07-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_dataingestionvault'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalDataBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pdf', models.FileField(upload_to='national_bridge/pdfs/')),
                ('is_processed', models.BooleanField(default=False)),
                ('records_synced', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': '3. National Data Bridge',
                'verbose_name_plural': '3. National Data Bridge',
            },
        ),
    ]
