# Generated by Django 4.2.1 on 2026-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_kebmockportal_kebmockresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='keb_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/keb/', verbose_name='Official KEB Logo'),
        ),
    ]
