# Generated by Django 4.2.1 on 2026-09-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parent_user_staff_user_schoolverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('document_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('pass_mark', models.PositiveIntegerField(default=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='api.learninglesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_quizzes', to='api.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_quizzes', to='api.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_topics', to='api.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_topics', to='api.subject')),
            ],
            options={
                'ordering': ['subject__name', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.learningquiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('answers_json', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.learningquiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_quiz_attempts', to='api.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_position_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='api.learninglesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.learningtopic'),
        ),
        migrations.CreateModel(
            name='LearningAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.learningassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assignment_submissions', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='learningassignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='api.learninglesson'),
        ),
        migrations.AddField(
            model_name='learningassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assignments', to='api.school'),
        ),
        migrations.AddField(
            model_name='learningassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assignments', to='api.subject'),
        ),
        migrations.AddIndex(
            model_name='learningtopic',
            index=models.Index(fields=['school', 'class_name', 'is_published'], name='api_learnin_school__5bd2f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.UniqueConstraint(fields=('student', 'lesson'), name='unique_learning_progress_student_lesson'),
        ),
        migrations.AddIndex(
            model_name='learninglesson',
            index=models.Index(fields=['topic', 'is_published'], name='api_learnin_topic_i_938b35_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningassignmentsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'assignment'), name='unique_learning_assignment_submission'),
        ),
    ]
