# Generated by Django 4.2.1 on 2026-06-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subject_options_remove_subject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpayledger',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolpost',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolpost',
            name='school_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School')], default='SECONDARY', max_length=10),
        ),
    ]
