# Generated by Django 6.0.5 on 2026-05-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bioandcareer_options_alter_feestracker_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestracker',
            name='student',
        ),
        migrations.RemoveField(
            model_name='nationalranking',
            name='student',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='achievements',
            new_name='school_achievements',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='motto',
            new_name='school_motto',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_top_teaching',
        ),
        migrations.RemoveField(
            model_name='school',
            name='national_rating',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ai_competency_index',
        ),
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.TextField(default='Active Learner'),
        ),
        migrations.AddField(
            model_name='student',
            name='district_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='future_career',
            field=models.CharField(default='Professional', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='national_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_comment',
            field=models.TextField(default='I will succeed.'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_remark',
            field=models.TextField(default='Performing well.'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fees_due',
            field=models.IntegerField(default=1200000),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fees_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI 1'), ('AOI2', 'AOI 2'), ('MidTerm', 'Mid-Term'), ('AOI3', 'AOI 3'), ('AOI4', 'AOI 4'), ('EOT', 'End of Term')], default='AOI1', max_length=20),
        ),
        migrations.DeleteModel(
            name='BioAndCareer',
        ),
        migrations.DeleteModel(
            name='FeesTracker',
        ),
        migrations.DeleteModel(
            name='NationalRanking',
        ),
    ]
