# Generated by Django 4.2.1 on 2026-06-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_schoolpayledger_is_printed_schoolpost_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BursarTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '1. NATIONAL BURSAR TERMINAL',
                'verbose_name_plural': '1. NATIONAL BURSAR TERMINAL',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='school',
            name='stamp_color',
            field=models.CharField(default='#002366', help_text='Hex color for digital stamp', max_length=20),
        ),
    ]
