# Generated by Django 6.0.5 on 2026-05-20 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_feestracker_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district_rank',
        ),
        migrations.RemoveField(
            model_name='student',
            name='future_career',
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_rank',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_comment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher_remark',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_fees_due',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_fees_paid',
        ),
        migrations.AddField(
            model_name='school',
            name='is_top_teaching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='national_rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='school',
            name='vision',
            field=models.TextField(default='To be a center of excellence.'),
        ),
        migrations.AddField(
            model_name='student',
            name='ai_competency_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_achievements',
            field=models.TextField(default='Leading in academic standards.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Primary', 'Primary/PLE'), ('Secondary_O', 'Secondary (CBC)'), ('Secondary_A', 'Secondary (UNEB)'), ('International', 'International'), ('Higher', 'University/Vocational')], max_length=50),
        ),
        migrations.CreateModel(
            name='BioAndCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_career', models.CharField(default='Professional', max_length=255)),
                ('achievements', models.TextField(default='Active Learner')),
                ('student_comment', models.TextField(default='Excellence is a choice.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeesTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees_due', models.IntegerField(default=1500000)),
                ('total_fees_paid', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='NationalRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_rank', models.IntegerField(default=0)),
                ('district_rank', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='api.student')),
            ],
        ),
    ]
