# Generated by Django 4.2.1 on 2026-10-02 09:22

import api.classroom_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_learningassignment_learninglesson_learningquiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject_name', models.CharField(blank=True, max_length=150)),
                ('class_name', models.CharField(db_index=True, max_length=100)),
                ('session_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('room_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('live', 'Live'), ('ended', 'Ended')], db_index=True, default='waiting', max_length=20)),
                ('settings', models.JSONField(default=api.classroom_models.classroom_default_settings)),
                ('educational_notice', models.TextField(default='This classroom is for educational purposes only. Content should be used for teaching, learning, revision, assessment, and academic discussion.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_classroom_sessions', to='api.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_sessions', to='api.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('topic_tags', models.JSONField(blank=True, default=list)),
                ('recording_url', models.URLField(blank=True)),
                ('transcript_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='api.classroomsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('staff', 'Staff')], default='parent', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('host_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_classroom_requests', to='api.staff')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.classroomsession')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_join_requests', to='api.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_join_requests', to='api.student')),
            ],
            options={
                'ordering': ['status', '-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='api.classroomsession')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_attendance', to='api.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_attendance', to='api.student')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['school', 'class_name', 'status'], name='api_classro_school__124f79_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['session_code', 'status'], name='api_classro_session_324d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomrecording',
            index=models.Index(fields=['is_published', 'created_at'], name='api_classro_is_publ_f07b84_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomjoinrequest',
            index=models.Index(fields=['session', 'status'], name='api_classro_session_c184ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('session', 'student'), name='unique_classroom_join_student'),
        ),
        migrations.AddIndex(
            model_name='classroomattendance',
            index=models.Index(fields=['session', 'joined_at'], name='api_classro_session_50afa9_idx'),
        ),
    ]
