# Generated by Django 4.2.1 on 2026-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_systemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name_plural': 'ACADEMIC HUB (MASTER GRID)'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'DAILY ATTENDANCE', 'verbose_name_plural': 'DAILY ATTENDANCE'},
        ),
        migrations.AlterModelOptions(
            name='attendancehub',
            options={'verbose_name': 'MARK DAILY ATTENDANCE', 'verbose_name_plural': 'MARK DAILY ATTENDANCE'},
        ),
        migrations.AlterModelOptions(
            name='commissionanalytics',
            options={'verbose_name_plural': 'MY COMMISSION TRACKER'},
        ),
        migrations.AlterModelOptions(
            name='feesreminder',
            options={'verbose_name': 'NATIONAL FEES REMINDERS', 'verbose_name_plural': 'NATIONAL FEES REMINDERS'},
        ),
        migrations.AlterModelOptions(
            name='financialcommandcenter',
            options={'verbose_name': 'NATIONAL FINANCIAL COMMAND', 'verbose_name_plural': 'NATIONAL FINANCIAL COMMAND'},
        ),
        migrations.AlterModelOptions(
            name='nationaldatabridge',
            options={'verbose_name': 'NATIONAL DATA BRIDGE', 'verbose_name_plural': 'NATIONAL DATA BRIDGE'},
        ),
        migrations.AlterModelOptions(
            name='nationalledger',
            options={'verbose_name_plural': 'NATIONAL UNEDITABLE LEDGER'},
        ),
        migrations.AlterModelOptions(
            name='sovereignparentregistry',
            options={'verbose_name': 'SOVEREIGN PARENT REGISTRY', 'verbose_name_plural': 'SOVEREIGN PARENT REGISTRY'},
        ),
        migrations.AlterModelOptions(
            name='sovereignprofessionalinsights',
            options={'verbose_name_plural': 'SOVEREIGN ANALYTICS (PRO)'},
        ),
        migrations.AlterModelOptions(
            name='sovereignregistry',
            options={'verbose_name': 'SOVEREIGN NATIONAL REGISTRY', 'verbose_name_plural': 'SOVEREIGN NATIONAL REGISTRY'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['level', 'name'], 'verbose_name': 'NATIONAL SUBJECT REGISTRY'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='api.subject'),
        ),
    ]
