# Generated by Django 4.2.1 on 2026-08-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_school_keb_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (UGX)')),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('stock_available', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'National Book Registry',
                'verbose_name_plural': 'National Book Registry',
            },
        ),
        migrations.CreateModel(
            name='NationalBookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(help_text='GPS or School Address', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('escrow_fee', models.DecimalField(decimal_places=2, help_text='10% Deposit', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pay'), ('PAID', 'Escrow Confirmed'), ('DISPATCHED', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nationalbook')),
            ],
            options={
                'verbose_name': 'Book Order Management',
                'verbose_name_plural': 'Book Order Management',
            },
        ),
    ]
