# Generated by Django 4.2.1 on 2026-06-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bursarterminal_school_stamp_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BursarTerminal',
        ),
        migrations.CreateModel(
            name='BursarTerminal',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL BURSAR TERMINAL',
                'verbose_name_plural': 'NATIONAL BURSAR TERMINAL',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
    ]
