# Generated by Django 4.2.1 on 2026-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_academicresultscenter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='secure_pin',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
