# Generated by Django 6.0.5 on 2026-05-20 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_student_achievements_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name': 'RESULTS CONTROL CENTRE', 'verbose_name_plural': '>>> 1. ENTER STUDENT MARKS HERE <<<'},
        ),
        migrations.RemoveField(
            model_name='bioandcareer',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='nationalranking',
            name='district_rank',
        ),
        migrations.RemoveField(
            model_name='school',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='school',
            name='district',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_top_teaching',
        ),
        migrations.RemoveField(
            model_name='school',
            name='national_rating',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_achievements',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_type',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='schoolpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ai_competency_index',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_national_topper',
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('SECONDARY_OLD', 'Secondary (Old UCE)'), ('SECONDARY_CBC', 'Secondary (New CBC)'), ('A_LEVEL', 'A-Level (UACE)'), ('UNIVERSITY', 'University (GPA)'), ('INTERNATIONAL', 'International (ACE)')], default='PRIMARY', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mark_obtained',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI1'), ('AOI2', 'AOI2'), ('MidTerm', 'MidTerm'), ('AOI3', 'AOI3'), ('AOI4', 'AOI4'), ('EOT', 'EOT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feestracker',
            name='total_fees_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nationalranking',
            name='national_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='linked_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='api.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='unique_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_motto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolpost',
            name='media_file',
            field=models.FileField(upload_to='feed/'),
        ),
        migrations.AlterField(
            model_name='schoolpost',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='account_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(help_text='e.g. Science, Humanity', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
