# Generated by Django 4.2.1 on 2026-10-05 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_classroomsession_classroomrecording_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationUploadAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('max_uploads', models.PositiveIntegerField(default=10)),
                ('uploads_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_upload_authorizations', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='EducationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('video_file', models.FileField(upload_to='education/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='education/thumbnails/')),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('education_level', models.CharField(blank=True, default='', max_length=100)),
                ('class_name', models.CharField(blank=True, default='', max_length=100)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('teacher_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='LESSON', max_length=100)),
                ('moderation_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('moderation_reason', models.TextField(blank=True, default='')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_education_videos', to=settings.AUTH_USER_MODEL)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='api.educationuploadauthorization')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_videos', to='api.school')),
            ],
        ),
    ]
