# Generated by Django 4.2.1 on 2026-08-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_nationalbook_nationalbookorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL PERFORMANCE ANALYTICS',
                'verbose_name_plural': 'NATIONAL PERFORMANCE ANALYTICS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
    ]
