# Generated by Django 4.2.1 on 2026-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_performanceanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='chairman_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Chairman Signature'),
        ),
    ]
