# Generated by Django 4.2.1 on 2026-06-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_bursarterminal_bursarterminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='api_password',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='docs/admission/'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='docs/birth/'),
        ),
        migrations.AddField(
            model_name='student',
            name='initial_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='student',
            name='ple_result_slip',
            field=models.FileField(blank=True, null=True, upload_to='docs/ple/'),
        ),
        migrations.AddField(
            model_name='student',
            name='uce_result_slip',
            field=models.FileField(blank=True, null=True, upload_to='docs/uce/'),
        ),
    ]
