# Generated by Django 4.2.1 on 2026-10-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_educationuploadauthorization_educationvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestracker',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
