# Generated by Django 6.0.5 on 2026-05-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_academicresultscenter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name': '>>> MARKS ENTRY HUB <<<', 'verbose_name_plural': '>>> MARKS ENTRY HUB <<<'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.AlterField(
            model_name='parent',
            name='linked_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_link', to='api.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('SECONDARY_OLD', 'Secondary (Old UCE)'), ('SECONDARY_CBC', 'Secondary (New CBC)'), ('A_LEVEL', 'A-Level (UACE)')], default='PRIMARY', max_length=20),
        ),
    ]
