# Generated by Django 4.2.1 on 2026-06-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_student_api_password_student_admission_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sector',
            field=models.CharField(choices=[('PRIMARY', 'Primary Level (PLE System)'), ('SECONDARY', 'Secondary Level (UCE/UACE System)'), ('VOCATIONAL', 'Vocational/Technical (DIT/BTVET)'), ('UNIVERSITY', 'Higher Education (NCHE/CGPA)')], default='SECONDARY', max_length=20),
        ),
    ]
