# Generated by Django 4.2.1 on 2026-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_code',
            field=models.CharField(blank=True, db_index=True, help_text="Student's SchoolPay PRN", max_length=100, null=True, unique=True),
        ),
    ]
