# Generated by Django 4.2.1 on 2026-08-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_school_chairman_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='combination_tag',
            field=models.CharField(blank=True, help_text='e.g. BCM, HEG', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_a_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_o_level',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(default='Standard Excellence', max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='templates/bg/')),
                ('opacity', models.FloatField(default=0.05)),
                ('theme_color', models.CharField(default='Royal Gold', max_length=50)),
                ('page_frame_enabled', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': 'REPORT DESIGNER VAULT',
            },
        ),
    ]
