# Generated by Django 4.2.1 on 2026-10-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feestracker_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresult',
            name='assessment_type',
            field=models.CharField(choices=[('NORMAL_EXAM', 'Normal Examinations'), ('KEB_MOCK', 'KEB Mock')], default='NORMAL_EXAM', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='academicresult',
            unique_together={('student', 'subject', 'assessment_type')},
        ),
        migrations.CreateModel(
            name='StaffWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=20)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('transaction_history', models.JSONField(blank=True, default=list)),
                ('last_transaction_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('unique_lesson_id', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='api.staff')),
            ],
        ),
    ]
