# Generated by Django 6.0.5 on 2026-05-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_academicresultscenter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name': 'Academic Result', 'verbose_name_plural': 'Academic Results'},
        ),
    ]
