# Generated by Django 4.2.1 on 2026-08-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subject_combination_tag_subject_is_a_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExchangeHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_file', models.FileField(upload_to='exchange/files/')),
                ('category', models.CharField(choices=[('STUDENTS', 'Student Bio'), ('MARKS', 'Academic Marks'), ('FEES', 'Financial Ledger')], default='STUDENTS', max_length=20)),
                ('exchange_type', models.CharField(choices=[('IMPORT', 'Import to System'), ('EXPORT', 'Export from Registry')], default='IMPORT', max_length=10)),
                ('processed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': 'National Data Exchange',
                'verbose_name_plural': 'National Data Exchange',
            },
        ),
        migrations.CreateModel(
            name='DataExchangeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Import & Export Center',
                'verbose_name_plural': 'Import & Export Center',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.dataexchangehub',),
        ),
    ]
