# Generated by Django 6.0.5 on 2026-05-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_academicresultscenter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name': 'Academic Result Hub', 'verbose_name_plural': 'Academic Result Hub'},
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('SECONDARY_OLD', 'Secondary (Old UCE)'), ('SECONDARY_CBC', 'Secondary (New CBC)'), ('A_LEVEL', 'A-Level (UACE)'), ('UNIVERSITY', 'University (GPA)')], default='PRIMARY', max_length=20),
        ),
    ]
