# Generated by Django 4.2.1 on 2026-08-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_student_full_name_alter_student_payment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NATIONAL LIVE FEED',
                'ordering': ['-date_found'],
            },
        ),
    ]
