# Generated by Django 4.2.1 on 2026-06-29 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovereignRegistry',
            fields=[
            ],
            options={
                'verbose_name': 'Sovereign Registry Explorer',
                'verbose_name_plural': 'Sovereign Registry Explorer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
    ]
