# Generated by Django 6.0.5 on 2026-05-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_academicresultscenter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
