# Generated by Django 4.2.1 on 2026-08-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_nationalupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('message_type', models.CharField(choices=[('SMS', 'SMS Text'), ('WHATSAPP', 'WhatsApp Message')], default='SMS', max_length=10)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': 'COMMUNICATION LOGS',
                'ordering': ['-timestamp'],
            },
        ),
    ]
