# Generated by Django 4.2.1 on 2026-06-29 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sovereignregistry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sovereignregistry',
            options={'verbose_name': 'Sovereign National Registry', 'verbose_name_plural': 'Sovereign National Registry'},
        ),
    ]
