# Generated by Django 4.2.1 on 2026-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_school_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationaldatabridge',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
