# Generated by Django 6.0.5 on 2026-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_schoolpost_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name_plural': '1. MARKS ENTRY HUB (By Student)'},
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('SECONDARY_OLD', 'Secondary (Old UCE)'), ('SECONDARY_CBC', 'Secondary (New CBC)'), ('A_LEVEL', 'A-Level (UACE)')], default='PRIMARY', max_length=20),
        ),
    ]
