# Generated by Django 6.0.5 on 2026-05-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_academicresultscenter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name_plural': '1. ACADEMIC RESULTS (MASTER HUB)'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.AddField(
            model_name='parent',
            name='current_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(default=256746594703, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='account_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum (A-E)'), ('UACE', 'UACE A-Level (Principal/Sub)'), ('ACE', 'ACE International (Mastery)'), ('UNIVERSITY', 'University (5.0 GPA)')], max_length=20),
        ),
    ]
