# Generated by Django 4.2.1 on 2026-08-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_student_is_active_alter_student_parent_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Salary')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PAYE/Tax')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid/Disbursed')], default='PENDING', max_length=20)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='api.staff')),
            ],
            options={
                'verbose_name': 'Staff Payroll Record',
                'verbose_name_plural': 'Staff Payroll Records',
            },
        ),
        migrations.CreateModel(
            name='PayrollCommand',
            fields=[
            ],
            options={
                'verbose_name': 'NATIONAL STAFF PAYROLL',
                'verbose_name_plural': 'NATIONAL STAFF PAYROLL',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.staffsalary',),
        ),
    ]
