# Generated by Django 4.2.1 on 2026-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_staffsalary_payrollcommand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicresult',
            name='aoi_2',
        ),
        migrations.RemoveField(
            model_name='academicresult',
            name='aoi_3',
        ),
        migrations.RemoveField(
            model_name='academicresult',
            name='aoi_4',
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_1_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='eot_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='mid_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='project_max',
            field=models.IntegerField(default=20),
        ),
    ]
