# Generated by Django 6.0.5 on 2026-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_academicresultscenter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_account_id',
            field=models.CharField(default=256000000000, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
