# Generated by Django 4.2.1 on 2026-06-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestracker',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_tracker', to='api.student'),
        ),
        migrations.AlterField(
            model_name='feestracker',
            name='total_fees_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='feestracker',
            name='total_fees_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
