# Generated by Django 6.0.5 on 2026-05-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_school_school_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_account_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
