# Generated by Django 4.2.1 on 2026-07-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_feestracker_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_pdf', models.FileField(upload_to='ingestion/pdfs/')),
                ('processed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
            options={
                'verbose_name': 'Imperial Data Ingestion',
                'verbose_name_plural': 'Imperial Data Ingestion',
            },
        ),
    ]
