# Generated by Django 4.2.1 on 2026-07-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dataingestionvault'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataingestionvault',
            options={'verbose_name': '1. Upload National PDF', 'verbose_name_plural': '1. Upload National PDF'},
        ),
        migrations.AlterModelOptions(
            name='sovereignregistry',
            options={'verbose_name': '2. Sovereign National Registry', 'verbose_name_plural': '2. Sovereign National Registry'},
        ),
    ]
