# Generated by Django 6.0.5 on 2026-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_school_school_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='otp_expiry',
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI1'), ('AOI2', 'AOI2'), ('MidTerm', 'MidTerm'), ('EOT', 'EOT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('UCE_NEW', 'UCE New'), ('UACE', 'UACE'), ('ACE', 'ACE'), ('UNIVERSITY', 'University')], max_length=20),
        ),
    ]
