# Generated by Django 4.2.1 on 2026-07-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_dataingestionvault_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataingestionvault',
            options={'verbose_name': '1. National Data Ingestion', 'verbose_name_plural': '1. National Data Ingestion'},
        ),
        migrations.AlterModelOptions(
            name='sovereignregistry',
            options={'verbose_name': 'Sovereign National Registry', 'verbose_name_plural': 'Sovereign National Registry'},
        ),
        migrations.AddField(
            model_name='dataingestionvault',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
    ]
