# Generated by Django 6.0.5 on 2026-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_parent_otp_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='current_otp',
        ),
        migrations.AddField(
            model_name='parent',
            name='secure_pin',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AddField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Light', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI1'), ('AOI2', 'AOI2'), ('MidTerm', 'MidTerm'), ('AOI3', 'AOI3'), ('AOI4', 'AOI4'), ('EOT', 'EOT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum (A-E)'), ('UACE', 'UACE A-Level (Principal/Sub)'), ('ACE', 'ACE International (Mastery)'), ('UNIVERSITY', 'University (5.0 GPA)')], max_length=20),
        ),
    ]
