# Generated by Django 6.0.5 on 2026-05-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_parent_current_otp_parent_secure_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolpost',
            name='description',
        ),
        migrations.AddField(
            model_name='school',
            name='total_revenue_collected',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is the Pillar', max_length=100),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
