# Generated by Django 4.2.1 on 2026-07-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_dataingestionvault_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='linked_student',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='secure_pin',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='security_motto',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registered_children', to='api.parent'),
            preserve_default=False,
        ),
    ]
