# Generated by Django 6.0.5 on 2026-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_schoolpost_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tax_amount',
            new_name='system_tax',
        ),
        migrations.AddField(
            model_name='school',
            name='gateway_subaccount_id',
            field=models.CharField(blank=True, help_text='The Settlement ID from the Payment Gateway for this school', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI1'), ('AOI2', 'AOI2'), ('MidTerm', 'MidTerm'), ('EOT', 'EOT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is our Sovereignty', max_length=100),
        ),
    ]
