# Generated by Django 4.2.1 on 2026-07-06 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_parent_linked_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_link',
        ),
        migrations.AddField(
            model_name='parent',
            name='linked_student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_link', to='api.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='secure_pin',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AddField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Light', max_length=100),
        ),
    ]
