# Generated by Django 4.2.1 on 2026-07-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_student_parent_link_parent_linked_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataIngestionVault',
        ),
    ]
