# Generated by Django 6.0.5 on 2026-05-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_amount_transaction_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTopPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='performers/')),
            ],
        ),
        migrations.AddField(
            model_name='schoolpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is the Future', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='gateway_subaccount_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.school'),
        ),
    ]
