# Generated by Django 6.0.5 on 2026-05-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_nationaltopperformer_schoolpost_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='system_tax',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(choices=[('AOI1', 'AOI1'), ('AOI2', 'AOI2'), ('MidTerm', 'MidTerm'), ('EOT', 'EOT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Sovereign', max_length=100),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('staff_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(default='Senior Instructor', max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_list', to='api.school')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='api.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='NationalRanking',
        ),
    ]
