# Generated by Django 4.2.1 on 2026-07-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_dataingestionvault'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsHub',
            fields=[
            ],
            options={
                'verbose_name': '0. NATIONAL OPERATIONS HUB',
                'verbose_name_plural': '0. NATIONAL OPERATIONS HUB',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
    ]
