# Generated by Django 6.0.5 on 2026-05-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_amount_paid_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
        migrations.AddField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='Connected to the local district community.'),
        ),
        migrations.AddField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_uneb_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide quality education for a better future.'),
        ),
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.CharField(default='⭐⭐⭐⭐⭐', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='Private / Boarding & Day', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='uneb_center_number',
            field=models.CharField(default='U0000', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='vision',
            field=models.TextField(default='A leading institution in academic excellence.'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='test_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New (A-E)'), ('UACE', 'UACE'), ('ACE', 'ACE'), ('UNIVERSITY', 'University')], max_length=20),
        ),
    ]
