# Generated by Django 6.0.5 on 2026-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_staff_gender_school_community_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicresult',
            name='mark_obtained',
        ),
        migrations.RemoveField(
            model_name='academicresult',
            name='test_period',
        ),
        migrations.RemoveField(
            model_name='school',
            name='community_info',
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0, verbose_name='AOI 1'),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0, verbose_name='AOI 2'),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0, verbose_name='AOI 3'),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0, verbose_name='AOI 4'),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0, verbose_name='END OF TERM'),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0, verbose_name='MID TERM'),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0, verbose_name='PROJECT WORK'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences'), ('ARTS', 'Arts'), ('GENERAL', 'General'), ('RELIGIOUS', 'Religious Studies'), ('VOCATIONAL', 'Vocational / Skills')], default='ARTS', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To empower learners with national values.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='A centre of academic excellence.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum (A-E)'), ('UACE', 'UACE A-Level (Principal/Sub)'), ('ACE', 'ACE International (Mastery)'), ('UNIVERSITY', 'University (5.0 GPA)')], max_length=20),
        ),
    ]
