# Generated by Django 6.0.5 on 2026-05-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_academicresult_mark_obtained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='school',
        ),
        migrations.RemoveField(
            model_name='nationaltopperformer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='school',
            name='gateway_subaccount_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_uneb_registered',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0, verbose_name='End of Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0, verbose_name='Mid Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0, verbose_name='CBC Project'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Sovereignty', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='Mission Statement Here'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='Vision Statement Here'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='Senior Teacher', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.school'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(related_name='assigned_teachers', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum'), ('UACE', 'UACE A-Level'), ('UNIVERSITY', 'University')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences'), ('ARTS', 'Arts'), ('GENERAL', 'General / Subsidiary'), ('RELIGIOUS', 'Religious Studies'), ('VOCATIONAL', 'Vocational / Skills')], default='ARTS', max_length=20),
        ),
        migrations.DeleteModel(
            name='BioAndCareer',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
