# Generated by Django 6.0.5 on 2026-05-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_staff_email_nationaltopperformer_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovereignProfessionalInsights',
            fields=[
            ],
            options={
                'verbose_name_plural': '⭐ SOVEREIGN ANALYTICS (PRO)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.RemoveField(
            model_name='school',
            name='community_info',
        ),
        migrations.RemoveField(
            model_name='school',
            name='gateway_subaccount_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_uneb_registered',
        ),
        migrations.RemoveField(
            model_name='schoolpost',
            name='description',
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('PRIMARY', 'Primary Level Only'), ('UCE', 'O-Level (Lower Secondary)'), ('UACE', 'A-Level (Upper Secondary)'), ('ACE', 'ACE International Mastery'), ('UNIVERSITY', 'Higher Institution / University'), ('ALL', 'Applicable to All Levels')], default='UCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Sovereignty', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='Instructor', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.school'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(related_name='assigned_teachers', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New (A-E)'), ('UACE', 'UACE (Principal)'), ('ACE', 'ACE International'), ('UNIVERSITY', 'University (GPA)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences (Physics, Bio, Chem, Agric, Math)'), ('ARTS', 'Arts (History, Geography, Literature)'), ('LANGUAGES', 'Languages (English, Kiswahili, Luganda, French, Arabic)'), ('GENERAL', 'General / Subsidiaries (GP, Sub-Math, ICT)'), ('RELIGIOUS', 'Religious Studies (CRE, IRE)'), ('VOCATIONAL', 'Vocational / Skills (Music, P.E, Woodwork, Nutrition)')], default='ARTS', max_length=50),
        ),
    ]
