# Generated by Django 6.0.5 on 2026-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_school_community_info_school_gateway_subaccount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioandcareer',
            name='student_comment',
        ),
        migrations.RemoveField(
            model_name='nationaltopperformer',
            name='level',
        ),
        migrations.AddField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(default='Limited access to digital resources.'),
        ),
        migrations.AddField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(default='To build a better Uganda.'),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(default='National Leader', max_length=255),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Sovereign', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='Deeply rooted in the local Ugandan community.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline, Sovereignty'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide high-quality education and national values.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='To be a leading center of academic and moral excellence.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences (Phy, Bio, Chem, Agric, Math)'), ('ARTS', 'Arts (Hist, Geo, Lit, Economics)'), ('LANGUAGES', 'Languages (Eng, Swahili, Luganda, French, Arabic)'), ('GENERAL', 'General / Subsidiaries (GP, Sub-Math, ICT)'), ('RELIGIOUS', 'Religious Studies (CRE, IRE)'), ('VOCATIONAL', 'Vocational / Skills (Music, Woodwork, Nutrition)')], default='ARTS', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('PRIMARY', 'Primary Level'), ('UCE', 'O-Level (Lower Secondary)'), ('UACE', 'A-Level (Upper Secondary)'), ('UNIVERSITY', 'Higher Institution'), ('ALL', 'All Levels')], default='UCE', max_length=20),
        ),
    ]
