# Generated by Django 6.0.5 on 2026-05-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_delete_sovereignprofessionalinsights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovereignProfessionalInsights',
            fields=[
            ],
            options={
                'verbose_name_plural': '⭐ SOVEREIGN ANALYTICS (PRO)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.AddField(
            model_name='school',
            name='gateway_subaccount_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='Senior Instructor', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0, verbose_name='AOI 1'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0, verbose_name='AOI 2'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0, verbose_name='AOI 3'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0, verbose_name='AOI 4'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0, verbose_name='End of Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0, verbose_name='Mid Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0, verbose_name='Project / CBC Work'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(default='Limited access to high-speed digital tools.'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(default='Software Mogul', max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(default='To lead the digital revolution in Africa.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Knowledge is Sovereignty', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='Deeply rooted in the local Ugandan community.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline, Sovereignty'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide high-quality education and national values.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='To be a leading center of academic and moral excellence.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_list', to='api.school'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum (A-E)'), ('UACE', 'UACE A-Level (Principal/Sub)'), ('ACE', 'ACE International'), ('UNIVERSITY', 'University (GPA)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences (Physics, Bio, Chem, Agric, Math)'), ('ARTS', 'Arts (History, Geography, Literature)'), ('LANGUAGES', 'Languages (English, Kiswahili, Luganda, French)'), ('GENERAL', 'General / Subsidiaries (GP, Sub-Math, ICT)'), ('RELIGIOUS', 'Religious Studies (CRE, IRE)'), ('VOCATIONAL', 'Vocational / Skills (Music, P.E, Woodwork, Nutrition)')], default='ARTS', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('PRIMARY', 'Primary Level'), ('UCE', 'O-Level (Lower Secondary)'), ('UACE', 'A-Level (Upper Secondary)'), ('ALL', 'All Levels')], default='UCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='api.school'),
        ),
    ]
