# Generated by Django 6.0.5 on 2026-05-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_sovereignprofessionalinsights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='gateway_subaccount_id',
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(default='Registry pending.'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(default='To build a legacy for Uganda.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum (A-E)'), ('UACE', 'UACE A-Level (Principal/Sub)'), ('UNIVERSITY', 'University (GPA 5.0)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences (Physics, Bio, Chem, Agric, Math)'), ('ARTS', 'Arts (History, Geography, Literature, Economics)'), ('LANGUAGES', 'Languages (English, Kiswahili, Luganda, French, Arabic)'), ('GENERAL', 'General / Subsidiaries (GP, Sub-Math, ICT)'), ('RELIGIOUS', 'Religious Studies (CRE, IRE)'), ('VOCATIONAL', 'Vocational / Skills (Music, P.E, Woodwork, Nutrition)')], default='ARTS', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.student'),
        ),
    ]
