# Generated by Django 6.0.5 on 2026-05-25 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_school_gateway_subaccount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationaltopperformer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='schoolpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0, verbose_name='Project Work'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(default='Leader', max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(default='Uganda'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Light', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='Deeply rooted in the Ugandan community.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide quality national education.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='A lead institution in academic excellence.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(to='api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New'), ('UACE', 'UACE'), ('UNIVERSITY', 'University')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences'), ('ARTS', 'Arts'), ('LANGUAGES', 'Languages'), ('GENERAL', 'General'), ('RELIGIOUS', 'Religious'), ('VOCATIONAL', 'Vocational')], default='ARTS', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('UCE', 'O-Level'), ('UACE', 'A-Level'), ('ALL', 'All Levels')], default='UCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.school'),
        ),
    ]
