# Generated by Django 6.0.5 on 2026-05-26 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_academicresult_aoi_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0, verbose_name='Project / CBC Work'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(default='Registry pending.'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(default='National Leader', max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(default='To build a better Uganda.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Sovereignty', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum (A-E)'), ('UACE', 'UACE A-Level (Principal/Sub)'), ('ACE', 'ACE International Mastery'), ('UNIVERSITY', 'University (GPA 5.0)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences (Physics, Bio, Chem, Agric, Math)'), ('ARTS', 'Arts (History, Geography, Literature, Economics)'), ('LANGUAGES', 'Languages (English, Kiswahili, Luganda, French, Arabic)'), ('GENERAL', 'General / Subsidiaries (GP, Sub-Math, ICT)'), ('RELIGIOUS', 'Religious Studies (CRE, IRE)'), ('VOCATIONAL', 'Vocational / Skills (Music, P.E, Woodwork, Nutrition)')], default='ARTS', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('PRIMARY', 'Primary Level'), ('UCE', 'O-Level (Lower Secondary)'), ('UACE', 'A-Level (Upper Secondary)'), ('ALL', 'All Levels')], default='UCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='api.school'),
        ),
    ]
