# Generated by Django 6.0.5 on 2026-05-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_academicresult_project_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='is_uneb_registered',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='school',
            name='followers_count',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='schoolpost',
            name='is_live_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolpost',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='system_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='security_motto',
            field=models.CharField(default='Education is Sovereign', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='Community Info'),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Core Values'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='Mission'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='Secondary', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='Vision'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='Instructor', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(to='api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('UCE_NEW', 'UCE New'), ('UACE', 'UACE'), ('UNIVERSITY', 'University')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Sciences'), ('ARTS', 'Arts'), ('LANGUAGES', 'Languages'), ('GENERAL', 'General'), ('RELIGIOUS', 'Religious'), ('VOCATIONAL', 'Vocational')], default='ARTS', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
