# Generated by Django 6.0.5 on 2026-05-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_is_uneb_registered_school_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(default='Kampala', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(default='North', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(default='Leader', max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(default='Uganda'),
        ),
        migrations.AlterField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='Deeply rooted in the local Ugandan community.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline, Sovereignty'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide high-quality education and national values.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('UNIVERSITY', 'University/Tertiary')], default='SECONDARY', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='To be a leading center of academic and moral excellence.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.school'),
        ),
    ]
