# Generated by Django 6.0.5 on 2026-05-27 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_school_district_staff_phone_student_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationaltopperformer',
            name='level',
        ),
        migrations.AddField(
            model_name='school',
            name='total_commission_earned',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='Tuition', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0, verbose_name='AOI 1'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0, verbose_name='AOI 2'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0, verbose_name='AOI 3'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0, verbose_name='AOI 4'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0, verbose_name='End of Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0, verbose_name='Mid Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0, verbose_name='Project Work'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum (A-E)'), ('UACE', 'UACE A-Level (Principal/Sub)'), ('UNIVERSITY', 'University (GPA 5.0)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Provide details for combinations or CBC skills.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='api.school'),
        ),
    ]
