# Generated by Django 6.0.5 on 2026-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_nationaltopperformer_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SovereignProfessionalInsights',
        ),
        migrations.CreateModel(
            name='NationalTreasury',
            fields=[
            ],
            options={
                'verbose_name': '💰 NATIONAL REVENUE LEDGER',
                'verbose_name_plural': '💰 NATIONAL REVENUE LEDGER (UNEDITABLE)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.transaction',),
        ),
        migrations.CreateModel(
            name='SovereignCommandCenter',
            fields=[
            ],
            options={
                'verbose_name': '👑 SOVEREIGN COMMAND CENTER',
                'verbose_name_plural': '👑 SOVEREIGN COMMAND CENTER (PROFIT TRACKER)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name_plural': '1. ENTER MARKS HERE (MASTER HUB)'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='community_info',
        ),
        migrations.RemoveField(
            model_name='school',
            name='core_values',
        ),
        migrations.RemoveField(
            model_name='school',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='school',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AddField(
            model_name='nationaltopperformer',
            name='level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='Secondary', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('UCE_NEW', 'UCE New'), ('UACE', 'UACE'), ('UNIVERSITY', 'University')], max_length=20),
        ),
    ]
