# Generated by Django 6.0.5 on 2026-05-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_delete_sovereignprofessionalinsights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovereignProfessionalInsights',
            fields=[
            ],
            options={
                'verbose_name_plural': '⭐ SOVEREIGN ANALYTICS (PRO)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name_plural': '1. ACADEMIC RESULTS (MASTER HUB)'},
        ),
        migrations.RemoveField(
            model_name='nationaltopperformer',
            name='level',
        ),
        migrations.AddField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='Deeply rooted in the local Ugandan community.'),
        ),
        migrations.AddField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline, Sovereignty'),
        ),
        migrations.AddField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide high-quality education and national values.'),
        ),
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.CharField(default='⭐⭐⭐⭐⭐', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='vision',
            field=models.TextField(default='To be a leading center of academic and moral excellence.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(default='North', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Provide details for combinations or CBC skills.'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0, verbose_name='AOI 1'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0, verbose_name='AOI 2'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0, verbose_name='AOI 3'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0, verbose_name='AOI 4'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0, verbose_name='End of Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0, verbose_name='Mid Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0, verbose_name='Project Work'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(default='Leader', max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(default='Uganda'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('UNIVERSITY', 'University/Tertiary')], default='SECONDARY', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New Curriculum (A-E)'), ('UACE', 'UACE A-Level (Principal/Sub)'), ('UNIVERSITY', 'University (GPA 5.0)')], max_length=20),
        ),
    ]
