# Generated by Django 6.0.5 on 2026-05-28 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_sovereignprofessionalinsights_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicresultscenter',
            options={'verbose_name_plural': '1. ENTER MARKS HERE (MASTER HUB)'},
        ),
        migrations.AlterModelOptions(
            name='nationaltreasury',
            options={'verbose_name_plural': '💰 NATIONAL REVENUE LEDGER'},
        ),
        migrations.AlterModelOptions(
            name='sovereigncommandcenter',
            options={'verbose_name_plural': '👑 SOVEREIGN COMMAND CENTER'},
        ),
        migrations.RemoveField(
            model_name='schoolpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='designation',
        ),
        migrations.AddField(
            model_name='nationaltopperformer',
            name='level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='National Hub Member'),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide quality education.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='Secondary', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='A lead institution.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='+256', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('UCE_NEW', 'UCE New'), ('UACE', 'UACE'), ('UNIVERSITY', 'University')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(default='Detailed curriculum skills.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.school'),
        ),
    ]
