# Generated by Django 6.0.5 on 2026-05-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_academicresultscenter_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NationalTreasury',
        ),
        migrations.DeleteModel(
            name='SovereignCommandCenter',
        ),
        migrations.CreateModel(
            name='CommissionAnalytics',
            fields=[
            ],
            options={
                'verbose_name_plural': '💰 MY COMMISSION TRACKER',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
        migrations.CreateModel(
            name='NationalLedger',
            fields=[
            ],
            options={
                'verbose_name_plural': '🛡️ NATIONAL UNEDITABLE LEDGER',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.transaction',),
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='Senior Instructor', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_1',
            field=models.FloatField(default=0, verbose_name='AOI 1'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_2',
            field=models.FloatField(default=0, verbose_name='AOI 2'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_3',
            field=models.FloatField(default=0, verbose_name='AOI 3'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='aoi_4',
            field=models.FloatField(default=0, verbose_name='AOI 4'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='eot_score',
            field=models.FloatField(default=0, verbose_name='End of Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='mid_term',
            field=models.FloatField(default=0, verbose_name='Mid Term'),
        ),
        migrations.AlterField(
            model_name='academicresult',
            name='project_work',
            field=models.FloatField(default=0, verbose_name='Project Work'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='challenges_faced',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='future_career',
            field=models.CharField(default='National Leader', max_length=255),
        ),
        migrations.AlterField(
            model_name='bioandcareer',
            name='student_inspiration',
            field=models.TextField(default='Ugandan Prosperity'),
        ),
        migrations.AlterField(
            model_name='nationaltopperformer',
            name='level',
            field=models.CharField(default='Primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='community_info',
            field=models.TextField(default='Deeply rooted in the local Ugandan community.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline, Sovereignty'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide high-quality education and national values.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='Secondary / Boarding', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='To be a leading center of academic and moral excellence.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registry', to='api.school'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary (PLE)'), ('UCE_NEW', 'UCE New'), ('UACE', 'UACE'), ('UNIVERSITY', 'University')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(default='Detailed curriculum skills and competencies.'),
        ),
    ]
