# Generated by Django 6.0.5 on 2026-05-29 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_academicresultscenter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('SICK', 'Sick')], default='PRESENT', max_length=10)),
                ('remarks', models.CharField(blank=True, help_text="e.g. 'Arrived at 9AM'", max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.student')),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendance',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceHub',
            fields=[
            ],
            options={
                'verbose_name': '✅ MARK DAILY ATTENDANCE',
                'verbose_name_plural': '✅ MARK DAILY ATTENDANCE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.attendance',),
        ),
    ]
