# Generated by Django 6.0.5 on 2026-05-29 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_staffpayroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='momo_number',
            field=models.CharField(blank=True, help_text='Alternative MoMo for Salary Payouts', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='secure_pin',
            field=models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=6),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(help_text='Primary Contact', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registry', to='api.school'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='api.subject'),
        ),
    ]
