# Generated by Django 6.0.5 on 2026-06-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_staff_momo_number_staff_secure_pin_alter_staff_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPayLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'verbose_name': '🛡️ SCHOOLPAY LEDGER',
            },
        ),
    ]
