# Generated by Django 6.0.5 on 2026-06-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_schoolpayledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='api_password',
            field=models.CharField(blank=True, help_text='Secret password for API sync', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, help_text='Provided by SchoolPay', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='api_password',
            field=models.CharField(blank=True, help_text='Secret password for API sync', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_code',
            field=models.CharField(blank=True, help_text="Student's SchoolPay PRN", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_code',
            field=models.CharField(blank=True, help_text='Provided by SchoolPay', max_length=20),
        ),
    ]
