# Generated by Django 6.0.5 on 2026-06-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_school_api_password_school_school_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCommandCenter',
            fields=[
            ],
            options={
                'verbose_name': '📊 NATIONAL FINANCIAL COMMAND',
                'verbose_name_plural': '📊 NATIONAL FINANCIAL COMMAND',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.school',),
        ),
    ]
