# Generated by Django 6.0.5 on 2026-06-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_financialcommandcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpayledger',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
