# Generated by Django 6.0.5 on 2026-06-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_schoolpayledger_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ussd_instructions',
            field=models.TextField(default='1. Dial *165#\n2. Select 4 (Payments)\n3. Select 3 (SchoolPay)\n4. Select 1 (Pay Fees)\n5. Enter PRN', help_text='Custom dialing steps for this specific school'),
        ),
    ]
