# Generated by Django 6.0.5 on 2026-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_school_ussd_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffpayroll',
            old_name='basic_salary',
            new_name='gross_salary',
        ),
        migrations.RenameField(
            model_name='staffpayroll',
            old_name='allowances',
            new_name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='school',
            name='community_info',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='staffpayroll',
            name='deductions',
        ),
        migrations.AddField(
            model_name='staff',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='staff/cvs/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='national_id_copy',
            field=models.ImageField(blank=True, null=True, upload_to='staff/ids/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='NSSF No.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tin_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='URA TIN'),
        ),
        migrations.AddField(
            model_name='staffpayroll',
            name='nssf_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='NSSF (5%)'),
        ),
        migrations.AddField(
            model_name='staffpayroll',
            name='paye_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PAYE (URA)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='api_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='core_values',
            field=models.TextField(default='Integrity, Excellence, Discipline'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(default='To provide high-quality education.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='ussd_instructions',
            field=models.TextField(default='1. Dial *165# (MTN) or *185# (Airtel)\n2. Select Fees & SchoolPay\n3. Select Pay Fees\n4. Enter PRN', help_text='Provide step-by-step dialing instructions for the Parent App'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='A lead institution of excellence.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='momo_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='secure_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
