# Generated by Django 4.2.1 on 2026-06-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_rename_basic_salary_staffpayroll_gross_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Which school does this administrator manage?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.school'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('SICK', 'Sick')], default='PRESENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='rating',
            field=models.CharField(default='⭐⭐⭐⭐⭐', max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_account_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='momo_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='NSSF No.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tin_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='URA TIN'),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='account_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_code',
            field=models.CharField(blank=True, help_text="Student's SchoolPay PRN", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_code',
            field=models.CharField(blank=True, help_text='Provided by SchoolPay', max_length=30),
        ),
    ]
