# Generated by Django 4.2.1 on 2026-10-07 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_feestracker_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DIRECT', 'One-to-one chat'), ('GROUP', 'Group chat'), ('BROADCAST', 'Broadcast'), ('AI', 'AI assistant')], default='DIRECT', max_length=12)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_connect_created_conversations', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='school_connect_conversations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_connect_conversations', to='api.school')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolConnectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('student_prn', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_prn_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_connect_identities', to='api.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_connect_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('voice_note', models.FileField(blank=True, upload_to='school_connect/voice_notes/%Y/%m/')),
                ('video', models.FileField(blank=True, upload_to='school_connect/videos/%Y/%m/')),
                ('media_status', models.CharField(choices=[('NONE', 'No media'), ('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='NONE', max_length=12)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('xog', 'Lusoga'), ('nyn', 'Runyankole'), ('sw', 'Swahili')], default='en', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_summary', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_connect_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4096, unique=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_connect_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_identifier', models.CharField(max_length=120)),
                ('verified', models.BooleanField(default=False)),
                ('decision', models.CharField(max_length=32)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_connect_fee_queries', to='api.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_connect_fee_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='chat_studen_user_id_59e9dd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolconnectuser',
            constraint=models.UniqueConstraint(condition=models.Q(('student_prn', ''), _negated=True), fields=('user', 'student_prn'), name='chat_unique_user_student_prn'),
        ),
    ]
